//
// Created by nt024762 on 12/14/2023.
//

#ifndef GRAPH_PUZZLE_GAME_NISANTASCIOGLU_MAIN_MAIN_H
#define GRAPH_PUZZLE_GAME_NISANTASCIOGLU_MAIN_MAIN_H


class main {


};


#endif //GRAPH_PUZZLE_GAME_NISANTASCIOGLU_MAIN_MAIN_H
